http.host: 0.0.0.0
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
pipeline.batch.delay: 50
pipeline.batch.size: 1000
pipeline.workers: ${PIPELINE_WORKERS}
xpack.monitoring.enabled: false
